name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - v1  # If you want to trigger the workflow on different branches like v1
  pull_request:
    branches:
      - main
      - v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/reelread:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/reelread:latest ${{ secrets.DOCKER_USERNAME }}/reelread:$(git rev-parse --short HEAD)

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/reelread:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/reelread:$(git rev-parse --short HEAD)